### ISSUE TITLE
Add GitHub profile hyperlinks to contributors' names

### ISSUE THREAD

**Issue by neeraj3029** [iiitv/cp-contests#12]

**Comment by thepushkarp** [comment]
![Screenshot from 2020-05-18 16-11-22](https://user-images.githubusercontent.com/42088801/82204355-5d365100-9922-11ea-9fb6-33ff2d6113a4.png)

@i-msid I think GH-Pages doesn't render Markdown emojis. Maybe we can use actual emoji `🔗` instead of `:link:` to fix this.

**Comment by neeraj3029** [comment]
This is weird, it appears fine here 
![image](https://user-images.githubusercontent.com/31539812/82204705-fd8c7580-9922-11ea-86a3-4e2666134995.png)

**Comment by thepushkarp** [comment]
@neeraj3029 for me somehow if shows fine in the README but emojis do not show on the page.

**Comment by neeraj3029** [comment]
I checked README file, my bad. Anyway won't it be better if we just add hyperlink to the name itself?

**Comment by thepushkarp** [comment]
Yeah, that's even better.
