### ISSUE TITLE
Fix bitSetGo v2.0 table view

### ISSUE THREAD

**Issue by thepushkarp** [iiitv/cp-contests#13]

**Comment by thepushkarp** [comment]
![Screenshot from 2020-05-17 19-29-28](https://user-images.githubusercontent.com/42088801/82149698-c9f31200-9874-11ea-81c9-06a1e812da90.png)

**Comment by thepushkarp** [comment]
The Problem table in bitSetGo v2.0 section on the website is not displayed correctly.

**Comment by nlok5923** [comment]
i would like to work this issue

**Comment by nlok5923** [comment]
@ishanksoni please assign it to me .

**Comment by ishanksoni** [comment]
@nlok5923  fix the issue :+1:
