### ISSUE TITLE
Link not rendering IIITV profile page.

### ISSUE THREAD

**Issue by nlok5923** [iiitv/cp-contests#18]
The link of IIITV open source Org present at the bottom of the readme is incorrect.

![Screenshot (1299)](https://user-images.githubusercontent.com/56120084/91792050-727d7580-ebc9-11ea-8cb0-1f88610725c2.png)

The address in the href attribute should be https://github.com/iiitv instead of https://github/iiitv

@iiitv/project-maintainers  i would like to work on it.

**Comment by aashutoshrathi** [comment]
GFI @nlok5923
